### ISSUE TITLE
Resultado do Desafio - Github_Search

### ISSUE THREAD

**Issue by lc-dev90** [Diegooliveyra/Github_Search#1]
Bom dia a todos!

Este é meu primeiro desafio aqui da plataforma DevChallenge, estou estudando programação a pouco tempo e já que possuo todo tempo livre, resolvi me dedicar full time a realização de projetos para treinar javascript react redux, etc.

Utilizei as seguintes tecnologias:

Html, Css (Styled Components), React Js, React Router, Axios, Redux, Axios e Material UI

O projeto está responsivo, e ele salva no localStorage a preferência do tema dark-mode. Todo o estado da aplicação estou gerenciando via redux (poderia ter feito com context ou outra ferramenta mas preferi redux para treinar porque tudo é muito novo pra mim).

Segue alguns prints do projeto:

![foto1](https://raw.githubusercontent.com/lc-dev90/github-search/master/design/Grava%C3%A7%C3%A3o%20de%20tela%20de%2016-07-2021%2005_31_03.gif)

![foto1](https://raw.githubusercontent.com/lc-dev90/github-search/master/design/Grava%C3%A7%C3%A3o%20de%20tela%20de%2016-07-2021%2005_53_19.gif)

[Demo](https://github-search-academic.netlify.app/)

Segue repositório link:
[Github](https://github.com/lc-dev90/github-search)

Obrigado pela atenção.

**Comment by Diegooliveyra** [comment]
Olá Luiz, parabéns pelo projeto, ficou sensacional!
Não deixe de compartilhar nas redes sócias, se quiser pode me marca no LinkedIn, grande abraço!

https://www.linkedin.com/in/diego-de-oliveira-brito/

**Comment by lc-dev90** [comment]
Obrigado Diego, já estou começando outro projeto lá da plataforma para praticar bastante. Estou te seguindo no linkedin, um abraço!
